// Generated by Wrangler by running `wrangler types`

interface Env {
	VALUE_FROM_CLOUDFLARE: "Hello from Cloudflare";
	Stateful: DurableObjectNamespace<import("./build/server/index").Stateful>;
	DB: D1Database;
}
