workers_dev = true
name = "repro-worker"
compatibility_date = "2025-02-19"
compatibility_flags = ["nodejs_compat"]
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "repro-db"
database_id = "11c66c65-23f6-4ab1-96b1-38c085ca4fa2"
migrations_dir = "drizzle"

[[durable_objects.bindings]]
name = "Stateful"
class_name = "Stateful"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Stateful"]
